### ISSUE TITLE
bash script download broken

### ISSUE THREAD

**Issue by sdx23** [ewels/sra-explorer#32] opened 2021-05-21 13:01 UTC
In the tab "Bash script for downloading FastQ files" clicking on "Download" results in a bash-script with malformed shebang. The file contains three additional non-printable bytes at the very beginning (0xefbbbf).

See attachment (renamed to txt as required by github).
[sra_explorer_fastq_download.txt](https://github.com/ewels/sra-explorer/files/6522618/sra_explorer_fastq_download.txt)

**Comment by ewels** [comment] 2021-05-21 17:47
This is a new one! You're quite right, I can see it too (also confirmed with my own downloads):

<img src="https://user-images.githubusercontent.com/465550/119177276-634a9a80-ba6c-11eb-9c52-b77350dd91e3.png" width=400>

This is a UTF-16 `BOM` - [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark). It should just tell the system what encoding to use to read the file. I've never heard of it causing problems for anyone before.

What happens when you try to run the bash script? What operating system etc are you using? I tested running both files as executables locally (MacOS) and they worked fine.

I would guess that the easiest workaround is to run the scripts explicitly through the bash interpreter: `bash file.sh` instead of just `./file.sh`. Then the shebang shouldn't matter.

**Comment by colindaven** [comment] 2021-06-10 14:00
There's some other poorly formatted sections of the bash download, at least when I copy / paste it.

The shebang looks ok to me, but a linebreak is introduced after, not before curl -L

Thanks for a nice tool

```

ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR370/003/ERR3700263/ERR3700263_1.fastq.gz -o ERR3700263_Illumina_NovaSeq_6000_paired_end_sequencing_1.fastq.gz curl -L
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR370/003/ERR3700263/ERR3700263_2.fastq.gz -o ERR3700263_Illumina_NovaSeq_6000_paired_end_sequencing_2.fastq.gz curl -L
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR370/004/ERR3700264/ERR3700264_1.fastq.gz -o ERR3700264_Illumina_NovaSeq_6000_paired_end_sequencing_1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR370/004/ERR3700264/ERR3700264_2.fastq.gz -o ERR3700264_Illumina_NovaSeq_6000_paired_end_sequencing_2.fastq.gz
```

Might be a non-printing character again because a green char is showing up in nano on Linux.

**Comment by ewels** [comment] 2021-06-15 11:59
That one I can't replicate sorry. Works fine for me, in code editor or pasting into the terminal..

**Comment by ewels** [comment] 2021-06-15 12:00
I'm going to close this issue now as I don't think that there is anything that I can do to solve this problem. The tool is entirely browser based, and the extra characters and encoding is handled entirely by the user's web browser. I don't think that there is anything that can be done through the tool itself to affect these things.

Let me know if you have any ideas and I can reopen 👍🏻

**Closed as completed by ewels** 2021-06-15 12:00 UTC
